### ISSUE TITLE
how to use a yolov5 representation learning model?

### ISSUE THREAD

**Issue by tangsipeng** [j-marple-dev/AYolov2#54]
i do not quite understand how to use a yolov5 representation learning model of coco ? it supposed to be a pretrain model like imagenet pretrained?

**Comment by JeiKeiLim** [comment]
Thank you for asking. I forgot to mention that our model does not use pre-trained model. Our goal was to make an object detection model without pre-trained weights such as image-net. And representation learning is one way to improve backbone capability with limited amount of data.
Representation learning is still under progress and experimental but if you wish to try, you can first train backbone model with `train_repr.py` and train with `train.py` as you would train a scratch model but with backbone trained model.

**Comment by JeiKeiLim** [comment]
I'm closing this. Please open new issue if you have further question.
