### ISSUE TITLE
Custom dataset training

### ISSUE THREAD

**Issue by cosao** [j-marple-dev/AYolov2#57]
![image](https://user-images.githubusercontent.com/53820991/156979833-44943a06-de6b-42f0-b633-b53529f2fd75.png)
The class does not change during model training using custom data.
Please tell me how to solve this problem.

**Comment by JeiKeiLim** [comment]
The label names were supposed to be defined in `data.yaml` but we didn't have time to implement it.

For now label names are defined as [scripts.utils.constants.LABELS](https://github.com/j-marple-dev/AYolov2/blob/main/scripts/utils/constants.py#L17) 
It's temporary but you can add your own dataset label in the dictionary.

```python
LABELS = {
   "COCO": [ ... ],
   "VOC": [ ... ],
   "CUSTOM_DATASET": [ "label_1", "label_2", ... ]
}
```

And pass `dataset_name` argument in `LoadImagesAndLabels` class.

**Comment by cosao** [comment]
i solved problem, thanks for your answer
